name: dispgh atch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        type: choice
        description: "Log level"
        required: true
        options:
          - "debug"
          - "info"
          - "warning"
        default: "warning"
      matrix:
        type: string
        description: "Matrix"
        required: true
        default: '{ "version": [10, 12, 14], "os": ["ubuntu-latest", "windows-latest"] }'

jobs:
  strategy:
    matrix: ${{ fromJSON(github.event.inputs.matrix) }}
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}
